# Generated by Django 4.2.6 on 2023-10-18 18:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_passsword_change_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(default='DEV name', max_length=8),
        ),
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(default='DEV', max_length=8),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='thumnail_image_url',
            field=models.CharField(default='DEV thumbnail', max_length=512),
        ),
    ]
